version: '{build}'

platform:
  - x64

clone_folder: C:\gopath

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  GOPATH: C:\gopath
  GOROOT: C:\go\
  GOVERSION: 1.8

install:
  - ps: choco install ant
  - ps: $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
  - cmd: SET PATH=%GOPATH%\bin;%GOROOT%bin;%PATH%
  - java -version
  - ant -version
  - go version
  - go env

configuration:
  - Release

build_script:
  - ant release

artifacts:
  - path: 'bin\release\*'

notifications:
  - provider: Slack
    incoming_webhook:
      secure: M+uVE+sLWTTlZH2lfrCOFdQhkQAG7dMa4uE3Dso8lk19XLSGsWWy9cotGjalOqt2GnkSeYyqWTbnJy2GXAu8O8ClA4UqWZlvD+Cu0JDXgN8=
